-- Seeds the `sources` table with the 10 entries currently hardcoded in
-- app.research.deterministic_search.SOURCES, plus the per-kind extraction
-- template from _KIND_INSTRUCTIONS. preferred_tier reflects what each
-- source's fetch/extract path already does today: 1 = regex parser
-- (Chapel/GAMH/1015 Folsom), 2 = LLM extraction over a plain HTTP fetch
-- (Funcheap, the two food outlets), 4 = search fallback only (the two
-- Live Nation venues, Punch Line, and The Independent — all either
-- JS-only or Cloudflare-blocked). Safe to re-run (ON CONFLICT DO NOTHING).

insert into sources (label, city, url, kind, preferred_tier, parser_id, extraction_rules)
values
  ('The Fillmore', 'sf', 'https://thefillmore.com/shows/', 'venue', 4, null, $$This is {label}'s show listing. List every real upcoming show you find with its date and price if shown. For EVERY event from this source: set venue to "{label}" unless the listing clearly states a different specific venue, and set url to that show's own link if the listing gives one, otherwise set url to this exact page: {url}. Never leave venue or url blank for an event from this source — one of these two URLs always applies.$$),
  ('The Independent', 'sf', 'https://www.theindependentsf.com/calendar', 'venue', 4, null, $$This is {label}'s show listing. List every real upcoming show you find with its date and price if shown. For EVERY event from this source: set venue to "{label}" unless the listing clearly states a different specific venue, and set url to that show's own link if the listing gives one, otherwise set url to this exact page: {url}. Never leave venue or url blank for an event from this source — one of these two URLs always applies.$$),
  ('The Chapel', 'sf', 'https://thechapelsf.com/calendar/', 'venue', 1, 'chapel', $$This is {label}'s show listing. List every real upcoming show you find with its date and price if shown. For EVERY event from this source: set venue to "{label}" unless the listing clearly states a different specific venue, and set url to that show's own link if the listing gives one, otherwise set url to this exact page: {url}. Never leave venue or url blank for an event from this source — one of these two URLs always applies.$$),
  ('1015 Folsom', 'sf', 'https://1015.com/', 'venue', 1, '1015folsom', $$This is {label}'s show listing. List every real upcoming show you find with its date and price if shown. For EVERY event from this source: set venue to "{label}" unless the listing clearly states a different specific venue, and set url to that show's own link if the listing gives one, otherwise set url to this exact page: {url}. Never leave venue or url blank for an event from this source — one of these two URLs always applies.$$),
  ('Great American Music Hall', 'sf', 'https://gamh.com/calendar/', 'venue', 1, 'gamh', $$This is {label}'s show listing. List every real upcoming show you find with its date and price if shown. For EVERY event from this source: set venue to "{label}" unless the listing clearly states a different specific venue, and set url to that show's own link if the listing gives one, otherwise set url to this exact page: {url}. Never leave venue or url blank for an event from this source — one of these two URLs always applies.$$),
  ('Cobb''s Comedy Club', 'sf', 'https://www.cobbscomedy.com/shows', 'comedy', 4, null, $$This is {label}'s show listing. For each distinct performer/act, list only ONE entry — if that performer has multiple nights or showtimes in the listing, do NOT list each night separately; use their first/soonest date and note in your summary that it runs across multiple nights (e.g. 'runs Thu-Sat'). Include price if shown. For EVERY event from this source: set venue to "{label}", and set url to that show's own link if given, otherwise to this exact page: {url}. Never leave venue or url blank for an event from this source.$$),
  ('Punch Line SF', 'sf', 'https://www.punchlinecomedyclub.com/shows', 'comedy', 4, null, $$This is {label}'s show listing. For each distinct performer/act, list only ONE entry — if that performer has multiple nights or showtimes in the listing, do NOT list each night separately; use their first/soonest date and note in your summary that it runs across multiple nights (e.g. 'runs Thu-Sat'). Include price if shown. For EVERY event from this source: set venue to "{label}", and set url to that show's own link if given, otherwise to this exact page: {url}. Never leave venue or url blank for an event from this source.$$),
  ('Funcheap SF Events', 'sf', 'https://sf.funcheap.com/events/', 'fairs', 2, null, $$This is Funcheap's SF events listing. Only include fairs, street festivals, and markets that are ANNUAL, ONCE-A-YEAR special events — a named street fair or festival that happens one time per year. Do NOT include recurring weekly/monthly things like a regular farmers market, a weekly night market, or an ongoing weekly series. Include the date, price if shown, and venue if the listing names one. For EVERY event from this source: set url to that event's own page if the listing links to one, otherwise set url to this exact page: {url}. Never leave url blank for an event from this source.$$),
  ('SF Standard Food & Drink', 'sf', 'https://sfstandard.com/food-drink/', 'food', 2, null, $$This is from {label}, a news outlet. Only include specific, DATED food/dining EVENTS mentioned in its articles — pop-up dinners, food festivals, launch events, limited-run collaborations with an actual date. Do NOT include restaurant reviews, 'best of' lists, or evergreen articles with no specific event date. For EVERY event from this source: set url to that article's own link if given, otherwise to this exact page: {url}. Never leave url blank for an event from this source.$$),
  ('SFGate Food', 'sf', 'https://www.sfgate.com/food/', 'food', 2, null, $$This is from {label}, a news outlet. Only include specific, DATED food/dining EVENTS mentioned in its articles — pop-up dinners, food festivals, launch events, limited-run collaborations with an actual date. Do NOT include restaurant reviews, 'best of' lists, or evergreen articles with no specific event date. For EVERY event from this source: set url to that article's own link if given, otherwise to this exact page: {url}. Never leave url blank for an event from this source.$$)
on conflict (label) do nothing;
